#!/bin/bash
set -e

# Create system user/group
if ! id "bms-cockpit" &>/dev/null; then
    adduser --system --group \
            --home /var/lib/bms-cockpit \
            --shell /bin/bash \
            bms-cockpit

    usermod -aG video,input,tty bms-cockpit
fi

# Reload systemd units & enable service
systemctl daemon-reload
systemctl enable xserver.service
systemctl start xserver.service
