#!/bin/bash
set -e

# Create system user/group
if ! id "bms-cockpit" &>/dev/null; then
    adduser --system --group \
            --home /var/lib/bms-cockpit \
            --shell /bin/bash \
            bms-cockpit

    usermod -aG video,input,tty bms-cockpit
fi

# Reload systemd units
systemctl daemon-reload || true

# Enable and start xserver service
systemctl enable xserver.service || true
systemctl restart xserver.service || true

exit 0
